### ISSUE TITLE
Platform error remote.jvc_projectors - cannot import name 'GAMING_MODE_HDR_COMMAND'

### ISSUE THREAD

**Issue by rcdailey** [iloveicedgreentea/jvc_homeassistant#16]
I get this error:

> Platform error remote.jvc_projectors - cannot import name 'GAMING_MODE_HDR_COMMAND' from 'custom_components.jvc_projectors.const' (/config/custom_components/jvc_projectors/const.py)

Using this in my `configuration.yaml` file:

```yml
remote:
  - platform: jvc_projectors
    name: JVC Projector
    password: abc123
    host: 192.168.1.163
    scan_interval: 15
```

This appears to be a regression introduced in version 2.0.6. If I downgrade to v2.0.5, I do not get this error when I run Check Configuration in HASS.

**Comment by iloveicedgreentea** [comment]
Sorry about that I pushed a fix. Use HACS to update to 2.0.7 which fixes this.

**Comment by rcdailey** [comment]
Thanks. While I'm testing the new build, you should know that the README has a mistake in it. Instead of this for the sensor:

```yml
sensor:
  platform: template
  sensors:
```

It should be:

```yml
sensor:
  - platform: template
    sensors:
```
