### ISSUE TITLE
Service not found for jvc_projectors.gaming_mode_hdr

### ISSUE THREAD

**Issue by rcdailey** [iloveicedgreentea/jvc_homeassistant#17]
None of the four services work:

- Gaming mode HDR
- Gaming mode SDR
- Film mode HDR
- Film mode SDR

I get an error when I push the buttons on the remote you have in your README. For example, this button:

```yml
- type: button
  tap_action:
    action: call-service
    service: jvc_projectors.gaming_mode_hdr
    service_data: {}
    target:
      entity_id: remote.jvc_projector
  show_icon: false
  show_name: true
  hold_action:
    action: none
  name: Game HDR
```
