### ISSUE TITLE
No setup or config entry setup function defined.

### ISSUE THREAD

**Issue by davidm-glitch** [iloveicedgreentea/jvc_homeassistant#51]
Hello together,

I have this issue when starting Home Assistant:

```
Logger: homeassistant.setup
Quelle: setup.py:269
Erstmals aufgetreten: 17:45:11 (1 Vorkommnisse)
Zuletzt protokolliert: 17:45:11

Setup failed for custom integration 'jvc_projectors': No setup or config entry setup function defined.
```

This is in my configuration.yaml

```
remote:
  - platform: jvc_projectors
    name: "JVC N5"
    host: 192.168.1.37
    new_model: false
```

Any ideas what might be the issue?
